config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do

    # get '/post', to: 'posts#preview'
    collection do
      get 'my_posts_preview'
    end
    resources :comments
  end
  
  root 'posts#index'


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  def my_posts_preview
    @posts = current_user.posts
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment
  .comment_content
    .comment_text
      = comment.comment
    %p.comment_author= comment.user.email
  .comment_button
    = link_to "Edit Comment", edit_post_comment_path(comment.post, comment)
    = link_to "Delete Comment", [comment.post, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure you want to delete that comment?' }

app/views/comments/_comment_form.html.haml
.comment_form
  = simple_form_for([@post, @post.comments.build]) do |f|
    = f.text_area :comment, class: 'comment_form_input'
    .comment_form_submit
      = f.submit "Add Comment"
    .clearfix

app/views/comments/edit.html.haml
.h4 Edit Comment

= simple_form_for([@post, @comment]) do |f|
  = f.input :comment
  = f.submit

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.haml
.footer
  Footer
  / Narazie

app/views/layouts/application.html.haml
!!!
%html
%head
  .title 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700" rel="stylesheet">

  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

.body
  %header.main_header.clearfix
    #logo
      %p= link_to "Nice Forum. Sign up and write some posts!", root_path
    .button.pull-right
      - if user_signed_in?
        = link_to "New Post", new_post_path
        /
        / = link_to "//Profile //", my_posts_preview_posts_path

        = link_to "Log Out", destroy_user_session_path, method: :delete


        .btn-group
          %button.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
            Action
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "HTML", root_path
            %li
              = link_to "cjdsvjknv", root_path


      -else
        = link_to "Sign In", new_user_session_path
        /
        = link_to "Sign Up", new_user_registration_path

  .wrapper
    .p.notice= notice
    .p.alert= alert

  .wrapper
    = yield

    = render 'layouts/footer'

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.text_field :title, required: true, class: 'post_form_input'
  = f.text_area :content, required: true, class: 'post_content'
  .button_submit
    = f.submit
  .clearfix

app/views/posts/edit.html.haml
.h3
  Edit Post

= render 'form'

.cancel_link
  = link_to 'Cancel', post_path

app/views/posts/index.html.haml
.h3
  Posts:

- @posts.each do |post|
  .post
    .h4.post_title
      = link_to post.title, post
    .p.post_published
      Published at 
      = time_ago_in_words(post.created_at)
      ago, by 
      = post.user.email
      ,
      - if post.comments.count == 1
        1 comment
      - elsif post.comments.count > 1
        = post.comments.count
        comments
      - else
        no comments

/ = link_to "New Post", new_post_path

app/views/posts/my_posts_preview.html.haml
.h3 My Posts

- @posts.each do |post|
  .post
    .h4.post_title
      = link_to post.title, post

app/views/posts/new.html.haml
.h3
  New Post

= render 'form'

app/views/posts/show.html.haml
#post_show
  .post_title_show
    = @post.title
  .post_show_content
    = @post.content


  - if @post.user == current_user
    .button.pull-right
      .post_button
        = link_to "Edit", edit_post_path(@post)
      .post_button
        = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to dlete that post?"}
    / # = link_to "Home", root_path
    .clearfix


  #comments
    .h2= @post.comments.count
    = render @post.comments

    .h3 Reply
    = render "comments/comment_form"